# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20160716_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/logos/default.jpg', null=True, upload_to=''),
        ),
    ]
