# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20160716_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
